Repository juntossomosmais/venice, pull requests merged in 2020-06, with the labels that each got.

#19 chore: exported spinner to external use
  packages/react-ds/src/index.tsx
  packages/vue-ds/src/index.ts
Labels: enhancement

#22 feat: set large size as default and add medium button
  packages/core/models/button.model.ts
  packages/core/storybook/knobs/button.ts
  packages/react-ds/src/components/Button/Button.spec.tsx
  packages/react-ds/src/components/Button/Button.stories.mdx
  packages/react-ds/src/components/Button/Button.tsx
  packages/styles/components/Button.module.scss
  packages/vue-ds/src/components/Button/Button.spec.tsx
  packages/vue-ds/src/components/Button/Button.stories.mdx
  packages/vue-ds/src/components/Button/Button.vue
Labels: enhancement

#21 feat/pagination-react
  packages/core/docs/Pagination.md
  packages/core/models/icon.model.ts
  packages/core/models/index.ts
  packages/core/models/pagination.model.ts
  packages/core/storybook/knobs/index.ts
  packages/core/storybook/knobs/pagination.ts
  packages/react-ds/src/components/Button/Button.stories.mdx
  packages/react-ds/src/components/Pagination/Pagination.spec.tsx
  packages/react-ds/src/components/Pagination/Pagination.stories.mdx
  packages/react-ds/src/components/Pagination/Pagination.tsx
  packages/react-ds/src/components/Pagination/PaginationIndex.tsx
  packages/react-ds/src/components/Pagination/helpers/PaginationHelper.spec.ts
  packages/react-ds/src/components/Pagination/helpers/PaginationHelper.ts
  packages/react-ds/src/components/Pagination/icons/AngleLeft.tsx
  packages/react-ds/src/components/Pagination/icons/AngleRight.tsx
  packages/react-ds/src/components/Spinner/Spinner.stories.mdx
  packages/react-ds/src/components/Stepper/Stepper.stories.mdx
  packages/react-ds/src/index.tsx
  packages/styles/components/Icon.module.scss
  packages/styles/components/Pagination.module.scss
Labels: component

#24 feat/splitbutton
  .stylelintrc.json
  packages/core/docs/SplitButton.md
  packages/core/models/index.ts
  packages/core/models/split-button.model.ts
  packages/react-ds/.storybook/preview-head.html
  packages/react-ds/src/components/Button/Button.tsx
  packages/react-ds/src/components/SplitButton/SplitButton.spec.tsx
  packages/react-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/react-ds/src/components/SplitButton/SplitButton.tsx
  packages/styles/components/SplitButton.module.scss
  packages/vue-ds/.storybook/preview-head.html
  packages/vue-ds/src/components/SplitButton/SplitButton.spec.tsx
  packages/vue-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/vue-ds/src/components/SplitButton/SplitButton.vue
Labels: component

#30 fix: change path to generated build on vue
  packages/vue-ds/package.json
  packages/vue-ds/src/index.ts
Labels: bug

#31 fix: minimal adjusts to improve projects
  README.md
  packages/react-ds/src/components/Button/Button.tsx
  packages/react-ds/src/components/SplitButton/SplitButton.tsx
  packages/react-ds/src/components/Stepper/Stepper.tsx
  packages/styles/components/Button.module.scss
  packages/styles/components/SplitButton.module.scss
  packages/vue-ds/package.json
  packages/vue-ds/src/components/Button/Button.spec.tsx
  packages/vue-ds/src/components/Button/Button.vue
  packages/vue-ds/src/components/SplitButton/SplitButton.spec.tsx
  packages/vue-ds/src/components/SplitButton/SplitButton.vue
  packages/vue-ds/src/components/Stepper/Stepper.spec.tsx
  packages/vue-ds/src/components/Stepper/Stepper.vue
  packages/vue-ds/tsconfig.json
Labels: enhancement

#32 feat: add reset.css
  README.md
  packages/core/storybook/stories/1_Index.stories.mdx
  packages/core/storybook/stories/1_Theming.stories.mdx
  packages/core/storybook/styles/storybook.css
  packages/react-ds/.storybook/preview-head.html
  packages/react-ds/.storybook/preview.js
  packages/react-ds/src/stories/1_Installation.stories.mdx
  packages/styles/components/Button.module.scss
  packages/styles/components/Pagination.module.scss
  packages/styles/components/Spinner.module.scss
  packages/styles/components/SplitButton.module.scss
  packages/styles/components/Stepper.module.scss
  packages/styles/core/index.scss
  packages/styles/core/reset.scss
  packages/styles/core/screens.scss
  packages/styles/global/reset.css
  packages/styles/global/variables.scss
  packages/styles/package.json
  packages/styles/rollup.config.js
  packages/vue-ds/.storybook/preview-head.html
  packages/vue-ds/.storybook/preview.js
  packages/vue-ds/src/stories/1_Installation.stories.mdx
  yarn.lock
Labels: enhancement

#33 Feat/select
  .stylelintrc.json
  packages/core/docs/Select.md
  packages/core/models/select.model.ts
  packages/react-ds/package.json
  packages/react-ds/src/components/Select/Select.spec.tsx
  packages/react-ds/src/components/Select/Select.stories.mdx
  packages/react-ds/src/components/Select/Select.tsx
  packages/react-ds/src/components/icons/Caret.tsx
  packages/react-ds/src/components/icons/Icon.tsx
  packages/react-ds/src/components/icons/Store.tsx
  packages/react-ds/src/index.tsx
  packages/styles/components/Icon.module.scss
  packages/styles/components/Select.module.scss
  yarn.lock
Labels: component

#34 refactor: reordering context colors
  packages/core/storybook/stories/2_Colors.stories.mdx
Labels: documentation

#36 feat: add pipeline to deploy storybook on ghpages
  .github/workflows/build-and-tests.yml
  .github/workflows/ghpages.yml
  .github/workflows/nodejs.yml
  README.md
  package.json
Labels: enhancement
