Repository juntossomosmais/venice, pull requests merged in 2020-05, with the labels that each got.

#9 docs: add syntax highlight for react snippet
  README.md
Labels: documentation

#10 feat: add circle's button
  packages/core/models/button.model.ts
  packages/core/storybook/knobs/button.ts
  packages/react-ds/src/components/Button/Button.spec.tsx
  packages/react-ds/src/components/Button/Button.stories.mdx
  packages/react-ds/src/components/Button/Button.tsx
  packages/styles/components/Button.module.scss
  packages/vue-ds/src/components/Button/Button.spec.tsx
  packages/vue-ds/src/components/Button/Button.stories.mdx
  packages/vue-ds/src/components/Button/Button.vue
Labels: enhancement

#11 feat: add screen variables
  packages/core/storybook/stories/1_Theming.stories.mdx
  packages/core/storybook/stories/2_Screens.stories.mdx
  packages/styles/components/Button.module.scss
  packages/styles/components/Stepper.module.scss
  packages/styles/core/variables.scss
  packages/styles/global/variables.css
Labels: enhancement

#12 fix: change screen max container
  packages/core/storybook/stories/2_Screens.stories.mdx
  packages/styles/global/variables.css
Labels: enhancement

#13 fix: add lost href inside <a>
  packages/react-ds/src/components/Button/Button.spec.tsx
  packages/react-ds/src/components/Button/Button.tsx
  packages/vue-ds/src/components/Button/Button.spec.tsx
Labels: bug
