Repository juntossomosmais/venice, pull requests merged in 2020-08, with the labels that each got.

#49 [Refactor] Rollup config for React components
  packages/core/index.ts
  packages/core/tsconfig.json
  packages/react-ds/package.json
  packages/react-ds/rollup.config.js
  packages/react-ds/src/components/Button/index.spec.tsx
  packages/react-ds/src/components/Button/index.stories.mdx
  packages/react-ds/src/components/Button/index.tsx
  packages/react-ds/src/components/Input/index.spec.tsx
  packages/react-ds/src/components/Input/index.stories.mdx
  packages/react-ds/src/components/Input/index.tsx
  packages/react-ds/src/components/Pagination/PaginationIndex.tsx
  packages/react-ds/src/components/Pagination/index.spec.tsx
  packages/react-ds/src/components/Pagination/index.stories.mdx
  packages/react-ds/src/components/Pagination/index.tsx
  packages/react-ds/src/components/Select/index.spec.tsx
  packages/react-ds/src/components/Select/index.stories.mdx
  packages/react-ds/src/components/Select/index.tsx
  packages/react-ds/src/components/Spinner/index.spec.tsx
  packages/react-ds/src/components/Spinner/index.stories.mdx
  packages/react-ds/src/components/Spinner/index.tsx
  packages/react-ds/src/components/SplitButton/index.spec.tsx
  packages/react-ds/src/components/SplitButton/index.stories.mdx
  packages/react-ds/src/components/SplitButton/index.tsx
  packages/react-ds/src/components/Stepper/index.spec.tsx
  packages/react-ds/src/components/Stepper/index.stories.mdx
  packages/react-ds/src/components/Stepper/index.tsx
  packages/react-ds/src/index.ts
  packages/react-ds/src/index.tsx
  packages/react-ds/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: do-not-merge, enhancement

#70 [Feature] @juntossomosmais/venice-types on Vue components
  README.md
  packages/core/models/button.model.ts
  packages/core/models/dynamic-components.model.ts
  packages/core/models/field.model.ts
  packages/core/models/icon.model.ts
  packages/core/models/index.ts
  packages/core/models/pagination.model.ts
  packages/core/models/select.model.ts
  packages/core/models/spinner.model.ts
  packages/core/models/split-button.model.ts
  packages/core/models/stepper.model.ts
  packages/react-ds/src/components/Pagination/icons/AngleLeft.tsx
  packages/react-ds/src/components/Pagination/icons/AngleRight.tsx
  packages/vue-ds/package.json
  packages/vue-ds/src/components/Button/Button.vue
  packages/vue-ds/src/components/Pagination/Pagination.vue
  packages/vue-ds/src/components/Pagination/icons/AngleLeft.vue
  packages/vue-ds/src/components/Pagination/icons/AngleRight.vue
  packages/vue-ds/src/components/Spinner/Spinner.vue
  packages/vue-ds/src/components/SplitButton/SplitButton.vue
  packages/vue-ds/src/components/Stepper/Stepper.vue
  yarn.lock
Labels: enhancement

#71 Feat/add alert
  packages/core/docs/Alert.md
  packages/react-ds/src/components/Alert/index.spec.tsx
  packages/react-ds/src/components/Alert/index.stories.mdx
  packages/react-ds/src/components/Alert/index.tsx
  packages/react-ds/src/components/Icons/Bell.tsx
  packages/react-ds/src/components/Icons/Check.tsx
  packages/react-ds/src/components/Icons/FeaturedStar.tsx
  packages/react-ds/src/components/Icons/Icon.tsx
  packages/react-ds/src/components/Icons/Star.tsx
  packages/react-ds/src/components/Icons/Times.tsx
  packages/react-ds/src/components/Icons/TimesCircle.tsx
  packages/react-ds/src/components/Icons/index.tsx
  packages/react-ds/src/index.ts
  packages/styles/components/Alert.module.scss
  packages/styles/components/Icon.module.scss
  packages/venice-types/src/IAlert.ts
  packages/venice-types/src/index.ts
Labels: component

#72 Fixing alert
  packages/react-ds/src/components/Alert/index.tsx
  packages/styles/components/Alert.module.scss
Labels: component

#73 feat: add new monochrome color
  packages/core/storybook/stories/2_Colors.stories.mdx
  packages/styles/global/variables.scss
Labels: enhancement

#74 feat: add progress bar
  packages/core/docs/Progress.md
  packages/core/storybook/knobs/index.ts
  packages/core/storybook/knobs/progress.ts
  packages/react-ds/src/components/Progress/Progress.base.tsx
  packages/react-ds/src/components/Progress/Progress.wrapper.tsx
  packages/react-ds/src/components/Progress/index.spec.tsx
  packages/react-ds/src/components/Progress/index.stories.mdx
  packages/react-ds/src/components/Progress/index.tsx
  packages/styles/components/Progress.module.scss
  packages/venice-types/src/IProgress.ts
  packages/venice-types/src/index.ts
Labels: component

#76 HotFix: Progress component
  packages/react-ds/src/index.ts
Labels: bug

#77 Fix: progress display
  packages/core/storybook/knobs/progress.ts
  packages/react-ds/src/components/Progress/Progress.wrapper.tsx
  packages/react-ds/src/components/Progress/index.spec.tsx
  packages/react-ds/src/components/Progress/index.stories.mdx
  packages/venice-types/src/IProgress.ts
Labels: bug
