Repository juntossomosmais/venice, pull requests merged in 2020-09, with the labels that each got.

#93 button bold prop
  packages/react-ds/src/components/Button/index.stories.mdx
  packages/react-ds/src/components/Button/index.tsx
  packages/styles/components/Button.module.scss
  packages/venice-types/src/IButton.ts
Labels: enhancement

#98 feat: add paper
  packages/core/docs/Paper.md
  packages/react-ds/src/components/Paper/index.spec.tsx
  packages/react-ds/src/components/Paper/index.stories.mdx
  packages/react-ds/src/components/Paper/index.tsx
  packages/react-ds/src/index.ts
  packages/styles/components/Paper.module.scss
  packages/vue-ds/src/components/Paper/Paper.spec.tsx
  packages/vue-ds/src/components/Paper/Paper.stories.mdx
  packages/vue-ds/src/components/Paper/Paper.vue
  packages/vue-ds/src/index.ts
  yarn.lock
Labels: component

#101 fix/components-outline
  packages/styles/components/Button.module.scss
  packages/styles/components/Field.module.scss
  packages/styles/components/Select.module.scss
Labels: component, enhancement

#99 Feat/tooltip
  packages/core/storybook/styles/storybook.css
  packages/react-ds/src/components/Tooltip/index.spec.tsx
  packages/react-ds/src/components/Tooltip/index.stories.mdx
  packages/react-ds/src/components/Tooltip/index.tsx
  packages/react-ds/src/index.ts
  packages/styles/components/Tooltip.module.scss
  packages/venice-types/src/ITooltip.ts
  packages/venice-types/src/index.ts
Labels: component

#95 [Feature] Venice icons
  .gitignore
  package.json
  packages/core/storybook/stories/2_Icons.stories.mdx
  packages/react-ds/.storybook/preview.js
  packages/react-ds/package.json
  packages/venice-icons/README.md
  packages/venice-icons/config.json
  packages/venice-icons/package.json
  packages/venice-icons/src/buildPackage.js
  packages/venice-icons/styles/storybook.css
  packages/vue-ds/.storybook/preview.js
  packages/vue-ds/package.json
  scripts/moveFontelloAssets.js
  yarn.lock
Labels: enhancement, help wanted

#102 Feat/icons
  package.json
  packages/venice-icons/config.json
Labels: enhancement

#103 fix/tooltip - Arrow
  packages/styles/components/Tooltip.module.scss
Labels: component

#104 Feat/alert variants
  packages/react-ds/src/components/Alert/index.stories.mdx
  packages/react-ds/src/components/Alert/index.tsx
  packages/react-ds/src/components/Icons/Icon.tsx
  packages/styles/components/Alert.module.scss
  packages/styles/components/Icon.module.scss
  packages/venice-types/src/IAlert.ts
Labels: enhancement

#106 add breadcrumb
  packages/core/docs/Breadcrumb.md
  packages/react-ds/src/components/Breadcrumb/Breadcrumb.spec.tsx
  packages/react-ds/src/components/Breadcrumb/Breadcrumb.tsx
  packages/react-ds/src/components/Breadcrumb/BreadcrumbItem.tsx
  packages/react-ds/src/components/Breadcrumb/index.stories.mdx
  packages/react-ds/src/components/Breadcrumb/index.ts
  packages/react-ds/src/index.ts
  packages/styles/components/Breadcrumb.module.scss
  packages/venice-types/src/IBreadcrumb.ts
  packages/venice-types/src/index.ts
  packages/vue-ds/src/components/Breadcrumb/Breadcrumb.spec.tsx
  packages/vue-ds/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/vue-ds/src/components/Breadcrumb/Breadcrumb.vue
  packages/vue-ds/src/components/Breadcrumb/BreadcrumbItem.vue
  packages/vue-ds/src/index.ts
Labels: component

#107 feat: added icons
  packages/venice-icons/assets/eye-off.svg
  packages/venice-icons/assets/eye-on.svg
  packages/venice-icons/assets/refer.svg
  packages/venice-icons/config.json
Labels: enhancement

#108 Feat/add padlock icon
  README.md
  packages/venice-icons/assets/padlock.svg
  packages/venice-icons/config.json
Labels: enhancement
