Repository juntossomosmais/venice, pull requests merged in 2020-10, with the labels that each got.

#114 feat/tag
  packages/styles/components/Tag.module.scss
  packages/venice-types/src/ITag.ts
  packages/venice-types/src/index.ts
  packages/vue-ds/src/components/Button/Button.spec.tsx
  packages/vue-ds/src/components/Button/Button.vue
  packages/vue-ds/src/components/Tag/Tag.spec.tsx
  packages/vue-ds/src/components/Tag/Tag.stories.mdx
  packages/vue-ds/src/components/Tag/Tag.vue
  packages/vue-ds/src/index.ts
Labels: component, enhancement

#127 feat: added two icons from FA
  packages/venice-icons/config.json
Labels: enhancement

#128 feat: added new icons and update fontello-cli
  package.json
  packages/venice-icons/assets/close.svg
  packages/venice-icons/assets/double-ticket.svg
  packages/venice-icons/config.json
  yarn.lock
Labels: bug, enhancement

#130 feat/table-types
  packages/venice-types/src/ITable.ts
  packages/venice-types/src/index.ts
Labels: component

#131 feat/table
  packages/core/docs/Table.md
  packages/core/storybook/styles/storybook.css
  packages/react-ds/.storybook/preview.js
  packages/react-ds/src/components/Table/index.spec.tsx
  packages/react-ds/src/components/Table/index.stories.mdx
  packages/react-ds/src/components/Table/index.tsx
  packages/react-ds/src/index.ts
  packages/styles/components/CheckboxRadio.module.scss
  packages/styles/components/Table.module.scss
  yarn.lock
Labels: component

#133 feat/table
  packages/styles/components/Table.module.scss
Labels: component, enhancement

#132 Fix/button loading click
  packages/react-ds/src/components/Button/index.spec.tsx
  packages/react-ds/src/components/Button/index.tsx
  packages/vue-ds/src/components/Button/Button.spec.tsx
  packages/vue-ds/src/components/Button/Button.vue
Labels: bug
