Repository juntossomosmais/venice, pull requests merged in 2020-07, with the labels that each got.

#40 feat: splitbutton menu enhancement
  packages/core/models/split-button.model.ts
  packages/core/storybook/knobs/index.ts
  packages/core/storybook/knobs/split-button.ts
  packages/react-ds/src/components/Button/Button.tsx
  packages/react-ds/src/components/SplitButton/SplitButton.spec.tsx
  packages/react-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/react-ds/src/components/SplitButton/SplitButton.tsx
  packages/styles/components/SplitButton.module.scss
  packages/vue-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/vue-ds/src/components/SplitButton/SplitButton.vue
Labels: component, enhancement

#46 fix production's errors and improve markdown styles
  package.json
  packages/core/storybook/stories/1_Index.stories.mdx
  packages/core/storybook/styles/storybook.css
  packages/react-ds/.env
  packages/react-ds/.storybook/preview-body.html
  packages/react-ds/.storybook/preview.js
  packages/vue-ds/.storybook/preview-body.html
  packages/vue-ds/.storybook/preview.js
  yarn.lock
Labels: bug, enhancement

#47 fix/splitbutton-styles
  packages/core/storybook/knobs/split-button.ts
  packages/react-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/react-ds/src/components/SplitButton/SplitButton.tsx
  packages/styles/components/SplitButton.module.scss
  packages/vue-ds/src/components/SplitButton/SplitButton.stories.mdx
  packages/vue-ds/src/components/SplitButton/SplitButton.vue
Labels: component, enhancement

#48 feat/pagination-vue
  packages/core/helpers/Pagination/PaginationHelper.spec.ts
  packages/core/helpers/Pagination/index.ts
  packages/core/models/icon.model.ts
  packages/react-ds/src/components/Pagination/Pagination.stories.mdx
  packages/react-ds/src/components/Pagination/Pagination.tsx
  packages/styles/components/Pagination.module.scss
  packages/vue-ds/src/components/Pagination/Pagination.spec.tsx
  packages/vue-ds/src/components/Pagination/Pagination.stories.mdx
  packages/vue-ds/src/components/Pagination/Pagination.vue
  packages/vue-ds/src/components/Pagination/icons/AngleLeft.vue
  packages/vue-ds/src/components/Pagination/icons/AngleRight.vue
  packages/vue-ds/src/index.ts
Labels: component

#51 [Feature] New package for Venice typings
  .gitignore
  README.md
  packages/venice-types/README.md
  packages/venice-types/package.json
  packages/venice-types/src/IButton.ts
  packages/venice-types/src/IDynamicComponent.ts
  packages/venice-types/src/IField.ts
  packages/venice-types/src/IIcon.ts
  packages/venice-types/src/IPagination.ts
  packages/venice-types/src/ISelect.ts
  packages/venice-types/src/ISpinner.ts
  packages/venice-types/src/ISplitButton.ts
  packages/venice-types/src/IStepper.ts
  packages/venice-types/src/index.ts
  packages/venice-types/tsconfig.json
Labels: enhancement

#50 Feat/add mask into input
  jest.config.js
  packages/core/@types/index.d.ts
  packages/react-ds/jest.config.js
  packages/react-ds/package.json
  packages/react-ds/rollup.config.js
  packages/react-ds/src/components/Button/Button.tsx
  packages/react-ds/src/components/Input/Input.spec.tsx
  packages/react-ds/src/components/Input/Input.stories.mdx
  packages/react-ds/src/components/Input/Input.tsx
  tsconfig.json
  yarn.lock
Labels: component

#53 chore: normalize generic dev dependencies
  .gitignore
  package.json
  packages/core/package.json
  packages/react-ds/package.json
  packages/styles/package.json
  packages/vue-ds/package.json
  tsconfig.json
Labels: enhancement

#54 fix: remove zindex to avoid overlap
  packages/styles/components/Button.module.scss
Labels: bug
